Feat/index objects in objectariums
okp4/subql-okp4 pull request #8
Opened 2023-08-03 15:36 UTC by ErikssonJoakim

This PR implements a first version of the objectarium object indexer
- #7 

In a second PR we should add a pinned field so we can know who has pinned the object.

2023-08-03 19:06 UTC, ccamel requested changes

2023-08-04 07:48 UTC, ErikssonJoakim commented on schema.graphql
> +    contract: String!
Good point!

2023-08-04 07:50 UTC, ErikssonJoakim commented on schema.graphql
> +type StoredObject @entity {
We cannot name an entity object since this class name is reserved in JavaScript. But I see your point changing the name to something more neutral so I propose we rename is ObjectariumObject. It's a bit verbose but clearly lets you know what entity it is.

2023-08-04 09:46 UTC, ccamel commented on schema.graphql
> +type StoredObject @entity {
Oh, I see. It's fine. Let's do this. :relieved:

2023-08-04 09:47 UTC, ccamel approved these changes
LGTM! Thanks :+1:

2023-08-04 11:32 UTC, ccamel approved these changes

2023-08-04 14:29 UTC, amimart approved these changes
Seems fine! Great :)

2023-08-04 15:02 UTC, merged